macos_instance:
  image: big-sur-xcode

task:
  env:
    RUST_HOME: $HOME/rust
    CARGO_HOME: $RUST_HOME/.cargo
    RUSTUP_HOME: $RUST_HOME/.rustup
    PATH: $CARGO_HOME/bin:${PATH}
  registry_cache:
    folder: $RUST_HOME
    fingerprint_script: echo epic1
    populate_script: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --target aarch64-apple-darwin --verbose
  target_cache:
    folder: target
    fingerprint_script: cat Cargo.lock
  build_script:
    - cargo build --verbose --release --target aarch64-apple-darwin
    - cargo build --verbose --release --target x86_64-apple-darwin
    - lipo -create -output yj target/{aarch64,x86_64}-apple-darwin/release/yj
    - file yj
  before_cache_script: rm -rf $CARGO_HOME/registry/index
