language: rust

os:
  - linux
  - osx
  - windows

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_deploy: "./release-build.sh"

deploy:
  - provider: releases
    api_key:
      secure: "E0fTc4HHUWW/wIhx1FTWg3j3d3Kew0FvwfvkeWq4KPMqKea4ORO7rEYX3glKO9T+1l+htACxAkxO/jhwtU1U0JBe/G8wTXYdAw38BCjq1zJB0OY7RGGc0p7TUlvtexLRXMoRfrOWlVl5GYgS7EN4EAPPQuInnapPMpf0E2Rrmp1trk8hBpd/SzqqptoLdzxDWzjiTiD7m00xVaR+ZoiMIYS4WYYPQPbE96DWa9YZqUDx4BKsthYZtfiRe5rcSdXf130DNRENopbFNSE6jC4b1El4+WHyBpYm6bUpUsK9GFBHUXxXbkCEHZgX43GMG+oWHAweQ/bdg2nvZyfGYjsVyoiGdk/1twmUIV4CVuVZS63R4dO/RIlZYgTbPDCM2vK4VPkzRsNR1pikGlyTMnVoxKONJiCjZnBHcvv6LZcRNyVJZ+4mgRFYyZVj2rwVRBnZ5NdWdsBcaZe78pXtOYM8MSRZz3SXTbSNaac/LfvyGIHTBE1GpqFNQMgeHUqsHfU7Db/lxKtHCbF5wTcXR14+7yHkx80jbTuODU3/m3h7IaxdL5GCY3g9gGxX3fgiW53czivD9d0ZWy/6Ji5zu1rG8YH6DWm55wMrZrZnn41kRR/rUlNbvl1GHq4k+GTepZGUOgVdbthDdoGn53bMOSUq7UAUpiXA72JHMAATmh/aOR8="
    file_glob: true
    skip_cleanup: true
    file: yj.*
    on:
      repo: bruceadams/yj
      rust: stable
      tags: true
  - provider: cargo
    on:
      repo: bruceadams/yj
      os: linux
      rust: stable
      tags: true
    token:
      secure: FgPUujt8hRwZap1gCifMuV4N8bwqokPCWRiEufFUmPeqrDP+Hg21bcTOaKwmL4a6WO/63gZwzK4wOlVsMOS8pNOylm72Ju36+pd6B6ntPrB/Yx8gDkvMdLd9/a+QDMsL7UHd7oarTLEi+UDJGM0InH9CPmWVXX6nexlrNhHensas+7Doxwfh40B9bLSDdvm5JBy2L8f38i1voAjslxSKt9svksrJmZL/BtFkJJUB1WMSa+C75iK4955RbRPd6Z3Z7HwmmQFE2FBFoAru2xy13dQE372m4nyjFKQjNLZEKSDQsC+/NXKx7cPYSc381Kto5EwTbuJJsxrABSEVSH5r3TLQba6vrzSZPrvCrqapGHz5nuC+XUr/OzF1awagYbaNZ/Ry2ls8zBuouB02Sd9xJ99XOKFY+8/zTxwfxhTXaBkuAmRk/w8D6do52PX0FCXgOZyuqmW5GcWYhxsCwLSNatGYcvTu+tbls4AZ+ymFydq7rVmyaLJUp6qsfZltybHSLlRJzT9DrSWA/3JgNOuFATlZvnJKB84oJoHVzzZ3MGQY8JfpIhieoTOsd6tdjwk+yD4NZq618OqXLTza79rpG3X0tRJCkh3HML/srOEjHKHB9+V1T+R69nIHNuiVt5J/YuiYO0cnwuzo6yJEvaC5rpgrjWJria5WeAVpCUZdF34=
