language: rust

os:
  - linux
  - osx
  - windows

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_deploy: "./release-build.sh"

deploy:
  - provider: releases
    api_key:
      secure: ooTJ960odE0jVr6CIQ3sgQ///NRikakpnKyyG/9UaDcAc1L6m8oU+JWD7uXfiaGwO+yuQUlGW/Ih2yeBMN1WARqt2Z3Hr6y0rbVfDC9MU0nEq8lwQE99AzAvJLxegBFpWjuRCk1b0z0ZfuNbO5Y8LwpdDnqCGT2O7x3KqHNjBSQup+9bRju7vQPzSL3zz/jr1DmxPssgAb1eSSGjK32KowZuHLKBXkPuDWKeuL2/8GWda39l3InYtbT5s2b+8gimEqY/Bmvkx18O5hrIi8KIZLLzGhLTYdtujFgqqnhC2QRV1rTEVtDkoq1lFHfT08uRJ9JuNvfW1T24+UpBDUUOscMP8f96QI0C6fRmO2b1M2QR386NO1CWB0VUuhMxsgijVvLb+4BFWqbm4md2C0KfvK6MdJpS4UgjxU0EAIurtNhHAqHfkQA2omWaonNgphe2eiFXH9wwUxhK5EkQkU7Vzvh4e16GtgwKBDmPX/AxUePDdBNEiDhyhyfv3S0aN+qoyeqQriiae8k8tG+t9kGv7VrYbHKk+uTTV90paKwer3LN6jiVSH9OJGAG5N8jWvnOI6ksoV/Q+Ofo2hv0MgYY9nFI7OQAzPCfpq59ANrTG6JxY/icStOwUVJ32Lp+4fxjlwdB64U4enU1kPFYfUIM7t1DTV5UzbHfG9L7k6PEWzk=
    file_glob: true
    skip_cleanup: true
    file: yj.*
    on:
      repo: bruceadams/yj
      rust: stable
      tags: true
  - provider: cargo
    on:
      repo: bruceadams/yj
      os: linux
      rust: stable
      tags: true
    token:
      secure: FgPUujt8hRwZap1gCifMuV4N8bwqokPCWRiEufFUmPeqrDP+Hg21bcTOaKwmL4a6WO/63gZwzK4wOlVsMOS8pNOylm72Ju36+pd6B6ntPrB/Yx8gDkvMdLd9/a+QDMsL7UHd7oarTLEi+UDJGM0InH9CPmWVXX6nexlrNhHensas+7Doxwfh40B9bLSDdvm5JBy2L8f38i1voAjslxSKt9svksrJmZL/BtFkJJUB1WMSa+C75iK4955RbRPd6Z3Z7HwmmQFE2FBFoAru2xy13dQE372m4nyjFKQjNLZEKSDQsC+/NXKx7cPYSc381Kto5EwTbuJJsxrABSEVSH5r3TLQba6vrzSZPrvCrqapGHz5nuC+XUr/OzF1awagYbaNZ/Ry2ls8zBuouB02Sd9xJ99XOKFY+8/zTxwfxhTXaBkuAmRk/w8D6do52PX0FCXgOZyuqmW5GcWYhxsCwLSNatGYcvTu+tbls4AZ+ymFydq7rVmyaLJUp6qsfZltybHSLlRJzT9DrSWA/3JgNOuFATlZvnJKB84oJoHVzzZ3MGQY8JfpIhieoTOsd6tdjwk+yD4NZq618OqXLTza79rpG3X0tRJCkh3HML/srOEjHKHB9+V1T+R69nIHNuiVt5J/YuiYO0cnwuzo6yJEvaC5rpgrjWJria5WeAVpCUZdF34=
