[package]
name = "yj"
version = "0.4.0"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
edition = "2018"

[dependencies]
failure = "0.1"
serde_json = "1.0"
serde_yaml = "0.8"

[dependencies.structopt]
features = ["wrap_help"]
version = "0.2"
