[package]
name = "yj"
version = "0.7.7"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
edition = "2018"

description = "Command line tool that converts YAML to JSON"
license = "Apache-2.0"
homepage = "https://github.com/bruceadams/yj"
repository = "https://github.com/bruceadams/yj"


[dependencies]
failure = "0.1"
serde_json = "1.0"
serde_yaml = "0.8"

[dependencies.structopt]
features = ["wrap_help"]
version = "0.2"
