name: Release

on:
  push:
    tags: "*"

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  macos:
    needs: release
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: cargo build --release --verbose
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ release.steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/yj
          asset_name: yj.macos
          asset_content_type: application/octet-stream

  linux:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          rustup target add x86_64-unknown-linux-musl
          cargo build --release --target x86_64-unknown-linux-musl --verbose
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ release.steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/yj
          asset_name: yj.linux
          asset_content_type: application/octet-stream

  windows:
    needs: release
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: cargo build --release --verbose
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ release.steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/yj.exe
          asset_name: yj.exe
          asset_content_type: application/octet-stream
